# Default colors
[colors.primary]
background = '#000f00'
foreground = '#df61a5'

[colors.cursor]
text   = '#df61a5'
cursor = '#4dc8cd'

# Normal colors
[colors.normal]
black   = '#123e7c'
red     = '#ff0000'
green   = '#d300c4'
yellow  = '#f57800'
blue    = '#123e7c'
magenta = '#711c91'
cyan    = '#4dc8cd'
white   = '#d7d7d5'

# Bright colors
[colors.bright]
black   = '#1c61c2'
red     = '#ff0000'
green   = '#d300c4'
yellow  = '#f57800'
blue    = '#00ff00'
magenta = '#711c91'
cyan    = '#4dc8cd'
white   = '#d7d7d5'

# Cursor
[cursor.style]
shape = 'Beam'